#!/bin/bash

#################################################################################
#           Display SmartThings Serial Numbers for Alarmserver Devices
#                        
#                           Version 1.20210124
#
# Copyright 2021 Todd A. Austin
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.                        
#
##################################################################################

# Save directory we're running from

currentdir=$(pwd)
devdirname="stdevices"
stdevicespath=""

# Get location of devices directory

fflag=0

if [ ! -d "$devdirname" ]; then
	while [ $fflag -ne 1 ]; do
		echo -en "\n\e[97mEnter full pathname of stdevices directory: \e[0m"
		read stdevicespath
	
		if [ -d "$stdevicespath" ]; then
			fflag=1;
		else
			echo -e "\e[91mNot found - try again\e[0m"
		fi
	done
else
	stdevicespath=$devdirname
	
fi
echo
echo "Scanning device directory: $stdevicespath"
echo

devnum=1
notdone=1

cmd_p1="grep -n "
cmd_p2="-e \"serialNumber\""
cmd_p3="cut -d : -f3"

while [ $notdone -eq 1 ]; do

	chkdir="$stdevicespath""/device""$devnum"
	
	if [ -d "$chkdir" ]; then
		buildcmd="$cmd_p1""$chkdir""/device_info.json ""$cmd_p2"
		
		output=$($buildcmd | $cmd_p3)
		
		serialnum="${output//\"}"
		
		echo "Device""$devnum: "$serialnum
		
	else
		notdone=0
	fi

	devnum=$((devnum+1))
done
echo
